#!/bin/env php
<?php

/**
 * @author Marien Fressinaud <dev@marienfressinaud.fr>
 * @license http://www.gnu.org/licenses/agpl-3.0.en.html AGPL
 */

if (php_sapi_name() !== 'cli') {
    die('This script must be called from command line.');
}

$app_path = __DIR__;

include $app_path . '/vendor/autoload.php';

\Webubbub\Configuration::load('dotenv', $app_path);

$request = \Minz\Request::initFromCli($argv);

$application = new \Webubbub\Application();
$response = $application->run($request);

\Minz\Response::sendToCli($response);
