<?php $this->layout('base.phtml', ['title' => 'Welcome on Webubbub!']); ?>

<h1>Welcome on Webubbub!</h1>

<p>
    Webubbub is a <a href="https://www.w3.org/TR/websub/">Websub</a> hub.
</p>

<?php if ($is_public_hub): ?>
    <p>
        <strong>Important: this hub is public and doesn't require any registration.</strong>
    </p>
<?php else: ?>
    <p>
        <strong>Important: this hub is private and you can’t use it to distribute content.</strong>
    </p>
<?php endif; ?>

<p>
    If you have a blog, you can configure your <abbr>RSS</abbr> or Atom feed by
    adding this link element:
</p>

<pre>
<code>&lt;link href="<?= url_full('Requests#handle') ?>" rel="hub" /&gt;</code>
</pre>

<p>
    Aggregators that support Websub will soon discover the link and subscribe
    to this hub.
</p>

<p>
    Next time you'll publish an article, just send a POST request to the hub with the following parameters:
</p>

<ul>
    <li><code>hub.mode="publish"</code></li>
    <li><code>hub.url=&lt;URL of your feed&gt;</code> (that's important the
        URL is exactly the same than the <code>self</code> link in your feed)</li>
</ul>

<p>
    For instance, with curl:
</p>

<pre>
<code>curl -d "hub.mode=publish&amp;hub.topic=&lt;URL of your feed&gt;" -X POST <?= url_full('Requests#handle') ?></code>
</pre>

<p>
    It should work well but Webubbub is still young so please be comprehensive
    if you encounter bugs.
</p>

<p>
    <a href="https://github.com/flusio/Webubbub">source code</a>
</p>

<hr />

<p>
    <small>
        Webubbub is brought to you by Marien Fressinaud. Please consider
        support my work by <a href="https://flus.fr">taking a subscription to Flus</a>
        (in French), a service to aggregate, save and share links from all over
        the Web (based on <a href="https://github.com/flusio/flusio/">flusio</a>).
    </small>
</p>
