<?php $this->template('base.phtml', ['title' => 'Welcome on Webubbub!']); ?>

<h1>Welcome on Webubbub!</h1>

<p>
    Webubbub is a <a href="https://www.w3.org/TR/websub/">Websub</a> hub.
</p>

<p>
    … well, it’ll probably be in the future. This is the very beginning
    of this project, there is nothing more to see here.
</p>

<p>
    <a href="https://github.com/flusio/Webubbub">source code</a>
</p>

<hr />

<p>
    <small>
        Websub is brought to you by <a href="https://marienfressinaud.fr">Marien Fressinaud</a>.
        Please consider support my work by <a href="https://flus.io">taking a subscription to Flus</a>,
        a news aggregator service using <a href="https://freshrss.org">FreshRSS</a>.
    </small>
</p>
