name: Continuous Integration

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    NODOCKER: true
    COVERAGE: --coverage-text

jobs:
    build:
        name: PHP ${{ matrix.php-versions }} CI on ${{ matrix.operating-system }}

        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['8.2', '8.3']

        steps:
        - uses: actions/checkout@v2
          with:
              submodules: true

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ matrix.php-versions }}
              coverage: xdebug
              extensions: pdo

        - name: Install the dependencies
          run: make install

        - name: Run the linters
          run: make lint

        - name: Run the test suite
          run: make test
